stages:
  - test
  - build

test:
  statge: test
  image: node:20-alpine
  script:
    - npm ci
    - npm run test

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build -t clipmate:latest .